#!/bin/bash

# Definindo cores que serão usadas ao decorrer do script
RED='\033[0;31m'

echo
echo
echo "  ____ ____ ____ ____ ____ ____ ____ ____ ____ ____ "
echo " ||C |||R |||A |||W |||L |||I |||N |||G |||! |||! ||"
echo " ||__|||__|||__|||__|||__|||__|||__|||__|||__|||__||"
echo " |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|"
echo "made by"
echo "!"
echo "!pad1ryoshi"
echo "!brazillian hacker"
echo "!"
echo
echo


# Verificando se as ferramentas Katana e anew existem na máquina
if ! command -v katana &> /dev/null || ! command -v anew &> /dev/null; then
    echo "Erro: katana e/ou anew não estão instalados. Por favor, instale-os e tente novamente."
    exit 1
fi

# Verificando se o arquivo "subs.txt" existe no diretório
if [ ! -f subs.txt ]; then
    echo -e "'\033[0;31mErro!': subs.txt não encontrado. Por favor, coloque o arquivo subs.txt no diretório atual e tente novamente."
    exit 1
fi

# Solicitando a confirmação do usuário e iniciando o crawling
read -p "Inicializar o processo de crawling? [S/N] " p
resp=${p^^} # Converter resposta para maiúscula

if [ "$resp" != "S" ]; then
    echo "Crawling cancelado pelo usuário."
    exit 0
fi

echo "OBS: Pressione CTRL + C para parar o crawling!!!"

# Loop de crawling
while [ "$resp" == "S" ]; do
    echo "Iniciando cr4wl1ng"
    cat subs.txt | katana -jc -kf all -nc -ef png,jpg,jpeg,css,gif,ttf,woff,woff2,svg,eot,js | anew crawl.txt
    echo "Crawling finalizado! Deseja iniciar novamente? [S/N]"
    read p
    resp=${p^^} # Converter resposta para maiúscula
done

echo "Crawling finalizado!!!"
